// Build the terms, privacy and tokushoho pages from the app repo's legal.md,
// so the wording has one source. Usage: node tools/build-legal.cjs [path/to/legal.md]
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SOURCE = path.resolve(process.argv[2] || path.join(ROOT, "../memoria/docs/ops/legal.md"));
const ORIGIN = "https://memoria.stelladear.com";

const md = fs.readFileSync(SOURCE, "utf8").replace(/\r\n/g, "\n");
const [ja, en] = md.split(/^# Memoria Legal Documents \(English\)$/m);

// Split one language half into its "## " documents, keyed by heading.
function documents(text) {
  const docs = {};
  for (const part of text.split(/^## /m).slice(1)) {
    const [heading, ...rest] = part.split("\n");
    docs[heading.trim()] = rest.join("\n");
  }
  return docs;
}

const escape = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const inline = (s) => escape(s)
  .replace(/&lt;br&gt;/g, "<br>")
  .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
  .replace(/([\w.+-]+@[\w-]+\.[\w.]+)/g, '<a href="mailto:$1">$1</a>');

const updatedOf = (text) => (text.match(/^\*(?:最終更新|Last updated)：?:?\s*(\d{4}-\d{2}-\d{2})\*$/m) || [])[1];
const ja_date = (d) => d.replace(/^(\d{4})-0?(\d+)-0?(\d+)$/, "$1年$2月$3日");
const en_date = (d) => new Date(`${d}T00:00:00Z`).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" });

// The small slice of Markdown legal.md uses: ### headings, paragraphs (line breaks kept), lists, a table.
function body(text, headingTag) {
  const html = [];
  const blocks = text.split(/\n{2,}/).map((b) => b.trim()).filter(Boolean);
  for (const block of blocks) {
    if (/^-{3,}$/.test(block) || /^\*(最終更新|Last updated)/.test(block)) continue;
    if (block.startsWith("### ")) {
      html.push(`<${headingTag}>${inline(block.slice(4))}</${headingTag}>`);
    } else if (block.startsWith("- ")) {
      html.push(`<ul class="bullets">${block.split("\n").map((l) => `<li>${inline(l.replace(/^- /, ""))}</li>`).join("")}</ul>`);
    } else if (block.startsWith("|")) {
      const rows = block.split("\n").slice(2).map((l) => l.split("|").slice(1, -1).map((c) => c.trim()));
      html.push(`<dl class="facts">\n${rows.map(([k, v]) => `        <dt>${inline(k.replace(/\*\*/g, ""))}</dt><dd>${inline(v)}</dd>`).join("\n")}\n      </dl>`);
    } else {
      html.push(`<p>${block.split("\n").map(inline).join("<br>")}</p>`);
    }
  }
  return html.map((h) => `      ${h}`).join("\n");
}

const nav = (current) => [
  ["terms", "利用規約"],
  ["privacy", "プライバシーポリシー"],
  ["tokushoho", "特定商取引法に基づく表記"],
].map(([slug, label]) => `<li><a href="../${slug}/"${slug === current ? ' aria-current="page"' : ""}>${label}</a></li>`).join("\n    ");

function page({ slug, title, description, updated, sections, noindex }) {
  const url = `${ORIGIN}/${slug}/`;
  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}｜Memoria（メモリア）</title>
<meta name="description" content="${description}">
${noindex ? '<meta name="robots" content="noindex">\n' : ""}<meta name="theme-color" content="#0C1524">
<link rel="canonical" href="${url}">
<link rel="icon" type="image/png" sizes="32x32" href="../assets/brand/favicon-32.png">
<link rel="icon" type="image/png" sizes="96x96" href="../assets/brand/favicon-96.png">
<link rel="apple-touch-icon" href="../assets/brand/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/page.css">
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "@id": "${url}",
      "url": "${url}",
      "name": "${title}",
      "inLanguage": "ja",
      "dateModified": "${updated}",
      "isPartOf": {"@id": "${ORIGIN}/#website"},
      "about": {"@id": "${ORIGIN}/#app"}
    },
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Memoria", "item": "${ORIGIN}/"},
        {"@type": "ListItem", "position": 2, "name": "${title}", "item": "${url}"}
      ]
    }
  ]
}
</script>
</head>
<body>
<!-- Generated by tools/build-legal.cjs from memoria/docs/ops/legal.md. Edit the source, then rebuild. -->
<a class="skip-link" href="#main">本文へスキップ</a>
<header class="site-header">
  <a class="brand" href="../" aria-label="Memoria トップ"><img class="brand-wordmark" src="../assets/brand/memoria-wordmark.svg" alt="Memoria" width="1971" height="356"></a>
  <nav class="header-nav" aria-label="メインナビゲーション"><a href="../about/">Memoriaとは</a><a href="../memory/">記憶</a><a href="../calendar/">カレンダー</a><a class="nav-download" href="../#download">ダウンロード</a></nav>
</header>

<main id="main" tabindex="-1">
  <div class="page-hero">
    <div class="page-hero-inner">
      <nav aria-label="パンくずリスト"><ol class="page-crumbs"><li><a href="../">Memoria</a></li><li aria-current="page">${title}</li></ol></nav>
      <h1>${title}</h1>
      <p class="legal-updated">最終更新：<time datetime="${updated}">${ja_date(updated)}</time></p>
    </div>
  </div>

  <div class="page-body legal">
${sections}
  </div>
</main>

<footer>
  <a class="footer-brand" href="../" aria-label="Memoria トップ"><img class="brand-wordmark" src="../assets/brand/memoria-wordmark.svg" alt="Memoria" width="1971" height="356" loading="lazy"></a>
  <nav class="footer-site" aria-label="Memoriaについて"><ul class="footer-links"><li><a href="../about/">Memoriaとは</a></li><li><a href="../memory/">Memoriaの記憶</a></li><li><a href="../calendar/">カレンダー</a></li><li><a href="../ai-companion/">AIコンパニオンとは</a></li></ul></nav>
  <ul class="footer-links">
    ${nav(slug)}
  </ul>
  <p class="copyright">© StellaDear</p>
</footer>
</body>
</html>
`;
}

// A Japanese document with its English translation below, on one URL.
function bilingual({ slug, title, description, updated, jaText, enTitle, enText }) {
  const enUpdated = updatedOf(en) || updated;
  const sections = `    <section class="page-section" aria-label="${title}">
      <p class="legal-switch" lang="en"><a href="#en">English version</a></p>
${body(jaText, "h2")}
    </section>

    <section class="page-section" id="en" lang="en" aria-labelledby="en-title">
      <h2 id="en-title" class="legal-doc-title">${enTitle}</h2>
      <p class="legal-updated">Last updated: <time datetime="${enUpdated}">${en_date(enUpdated)}</time></p>
${body(enText, "h3")}
    </section>`;
  return page({ slug, title, description, updated, sections });
}

const jaDocs = documents(ja);
const enDocs = documents(en);

// legal.md dates the terms and privacy policy together at the end of the Japanese half.
const shared = updatedOf(ja.split(/^## プライバシーポリシー$/m)[1]);
const tokushohoUpdated = updatedOf(jaDocs["特定商取引法に基づく表記"]);
if (!shared || !tokushohoUpdated) throw new Error("legal.md: could not find the last-updated dates");

const outputs = {
  terms: bilingual({
    slug: "terms",
    title: "利用規約",
    updated: shared,
    description: "Memoria（メモリア）の利用規約です。対象年齢、AIが生成する内容の扱い、データの管理、有料サービス、禁止事項などを定めています。",
    jaText: jaDocs["利用規約"],
    enTitle: "Terms of Service",
    enText: enDocs["Terms of Service"],
  }),
  privacy: bilingual({
    slug: "privacy",
    title: "プライバシーポリシー",
    updated: shared,
    description: "Memoria（メモリア）のプライバシーポリシーです。収集する情報、外部サービスへのデータ送信、利用目的、データの削除について説明しています。",
    jaText: jaDocs["プライバシーポリシー"],
    enTitle: "Privacy Policy",
    enText: enDocs["Privacy Policy"],
  }),
  tokushoho: page({
    slug: "tokushoho",
    title: "特定商取引法に基づく表記",
    description: "Memoria（メモリア）の特定商取引法に基づく表記です。",
    updated: tokushohoUpdated,
    noindex: true,
    sections: `    <section class="page-section" aria-label="特定商取引法に基づく表記">\n${body(jaDocs["特定商取引法に基づく表記"], "h2")}\n    </section>`,
  }),
};

for (const [slug, html] of Object.entries(outputs)) {
  fs.mkdirSync(path.join(ROOT, slug), { recursive: true });
  fs.writeFileSync(path.join(ROOT, slug, "index.html"), html);
  console.log(`wrote ${slug}/index.html`);
}
